export const WORDS = [
  "REACT", "REDUX", "ROUTER", "STATE", "PROPS",
  "HOOKS", "ASYNC", "FETCH", "AXIOS", "QUERY",
  "STYLE", "TAILWIND", "SASS", "LESS", "CSS",
  "HTML", "JAVASCRIPT", "TYPESCRIPT", "NODE", "EXPRESS"
];

